/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ForcedecksRouteImport } from './routes/forcedecks'
import { Route as DoctorReferralsRouteImport } from './routes/doctor-referrals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AthleticPerformanceRouteImport } from './routes/athletic-performance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcedecksRoute = ForcedecksRouteImport.update({
  id: '/forcedecks',
  path: '/forcedecks',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReferralsRoute = DoctorReferralsRouteImport.update({
  id: '/doctor-referrals',
  path: '/doctor-referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleticPerformanceRoute = AthleticPerformanceRouteImport.update({
  id: '/athletic-performance',
  path: '/athletic-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletic-performance': typeof AthleticPerformanceRoute
  '/contact': typeof ContactRoute
  '/doctor-referrals': typeof DoctorReferralsRoute
  '/forcedecks': typeof ForcedecksRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletic-performance': typeof AthleticPerformanceRoute
  '/contact': typeof ContactRoute
  '/doctor-referrals': typeof DoctorReferralsRoute
  '/forcedecks': typeof ForcedecksRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletic-performance': typeof AthleticPerformanceRoute
  '/contact': typeof ContactRoute
  '/doctor-referrals': typeof DoctorReferralsRoute
  '/forcedecks': typeof ForcedecksRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/athletic-performance'
    | '/contact'
    | '/doctor-referrals'
    | '/forcedecks'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/athletic-performance'
    | '/contact'
    | '/doctor-referrals'
    | '/forcedecks'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/athletic-performance'
    | '/contact'
    | '/doctor-referrals'
    | '/forcedecks'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AthleticPerformanceRoute: typeof AthleticPerformanceRoute
  ContactRoute: typeof ContactRoute
  DoctorReferralsRoute: typeof DoctorReferralsRoute
  ForcedecksRoute: typeof ForcedecksRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forcedecks': {
      id: '/forcedecks'
      path: '/forcedecks'
      fullPath: '/forcedecks'
      preLoaderRoute: typeof ForcedecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-referrals': {
      id: '/doctor-referrals'
      path: '/doctor-referrals'
      fullPath: '/doctor-referrals'
      preLoaderRoute: typeof DoctorReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletic-performance': {
      id: '/athletic-performance'
      path: '/athletic-performance'
      fullPath: '/athletic-performance'
      preLoaderRoute: typeof AthleticPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AthleticPerformanceRoute: AthleticPerformanceRoute,
  ContactRoute: ContactRoute,
  DoctorReferralsRoute: DoctorReferralsRoute,
  ForcedecksRoute: ForcedecksRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
